"use client";

import { useState } from "react";

export default function ResultSection() {
  const [split, setSplit] = useState(50);
  const updateSplit = (clientX: number, element: HTMLDivElement) => { const bounds = element.getBoundingClientRect(); setSplit(Math.min(96, Math.max(4, ((clientX - bounds.left) / bounds.width) * 100))); };
  return <section className="bg-[#0b2947] px-6 py-24 text-white md:px-10 md:py-36"><div className="mx-auto max-w-[1600px]" data-reveal><p className="eyebrow mb-5 text-[#8de6ff]">03 · The result</p><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><h2 className="max-w-3xl text-balance text-[clamp(3rem,5.4vw,5.4rem)] font-light uppercase leading-[.88] tracking-[-.055em]">Drag to reveal what the model recovers.</h2><p className="max-w-sm text-sm leading-6 text-[#b4d4e5]">Same coastal tile, two resolutions. Compare the raw observation with the reconstructed signal.</p></div><div className="relative mt-10 aspect-[4/3] min-h-[240px] w-full sm:mt-12 sm:aspect-[16/8.2] sm:min-h-[300px] select-none overflow-hidden border border-[#72c8ee]/35 bg-[#061323] touch-none" onPointerMove={(e) => { if (e.buttons === 1) updateSplit(e.clientX, e.currentTarget); }} onPointerDown={(e) => { e.currentTarget.setPointerCapture(e.pointerId); updateSplit(e.clientX, e.currentTarget); }} role="slider" aria-label="Compare input and super-resolution output" aria-valuemin={4} aria-valuemax={96} aria-valuenow={Math.round(split)} tabIndex={0} onKeyDown={(e) => { if (e.key === "ArrowLeft") setSplit((v) => Math.max(4, v - 4)); if (e.key === "ArrowRight") setSplit((v) => Math.min(96, v + 4)); }}><img src="/samples/preview_after.png" alt="TerraSharp super-resolution output" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-y-0 left-0 overflow-hidden" style={{ width: `${split}%` }}><img src="/samples/preview_before.png" alt="Raw medium-resolution input" className="h-full w-full max-w-none object-cover" style={{ width: `${100 / (split / 100)}%` }} /></div><div className="pointer-events-none absolute inset-y-0 z-10 w-px bg-[#8de6ff] shadow-[0_0_18px_rgba(141,230,255,.8)]" style={{ left: `${split}%` }}><div className="absolute left-1/2 top-1/2 flex size-11 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-[#8de6ff]/70 bg-[#061323] text-sm text-[#8de6ff] shadow-xl">↔</div></div><div className="absolute bottom-5 left-5 border border-[#72c8ee]/35 bg-[#061323]/80 px-3 py-2 font-mono text-[9px] uppercase tracking-[.14em] text-[#d9f4ff]">Raw input · 10m</div><div className="absolute bottom-5 right-5 border border-[#18c8c1]/45 bg-[#061323]/80 px-3 py-2 font-mono text-[9px] uppercase tracking-[.14em] text-[#8de6ff]">Reconstructed · &lt;4m</div></div></div></section>;
}
